const express = require('express')
const pages = require('../controllers/page.controller')
const checkout = require('../controllers/checkout.controller')
const interests = require('../controllers/interest.controller')
const media = require('../controllers/media.controller')
const { requireAuth } = require('../middlewares/auth.middleware')

const router = express.Router()

router.get('/', pages.home)
router.get('/login', pages.login)
router.get('/cadastro', pages.register)
router.get('/dashboard', requireAuth, pages.dashboard)
router.get('/confirmaremail', pages.confirmEmail)
router.get('/esquecisenha', pages.forgotPassword)
router.get('/produto', pages.legacyListingDetails)
router.get('/media/anuncios/:id', media.listingImage)
router.get('/anuncios/:slug/interesse', requireAuth, interests.show)
router.post('/anuncios/:slug/interesse', requireAuth, interests.create)
router.get('/interesses/enviado/:id', requireAuth, interests.confirmation)
router.get('/interesses', requireAuth, interests.received)
router.get('/anuncios/:slug/checkout', requireAuth, checkout.show)
router.post('/anuncios/:slug/checkout', requireAuth, checkout.create)
router.get('/pedidos/:id', requireAuth, checkout.confirmation)
router.get('/anuncios/:slug', pages.listingDetails)
router.get('/contato', pages.contact)
router.post('/confirmaremail', pages.confirmEmailUnavailable)
router.post('/esquecisenha', pages.forgotPasswordUnavailable)
router.post('/contato', pages.contactUnavailable)

module.exports = router
